### ISSUE TITLE
How do I add legends to memprof plots?

### ISSUE THREAD

**Issue by arne-cl** [jmdana/memprof#11]
Dear Jose,

thanks a lot for providing this library!

On the [http://jmdana.github.io/memprof/](memprof website), your example plot has a legend,
while your library doesn't seem to add them by default (your README on github doesn't have them, either). How can I enable them?

Best regards,
Arne

**Comment by jmdana** [comment]
Hi Arne,

They are enabled by default... unless there is a bug!

It seems that something changed in matplotlib and broke my code. I have just pushed a bugfix and it is working again. Could you please let me know if it also works for you?

Thanks a lot for your feedback!
Jose.
