### ISSUE TITLE
documentation unclear

### ISSUE THREAD

**Issue by DavoudTaghawiNejad** [jmdana/memprof#13]
Hello,

In the documentation its unclear that the graph shows the memory usage of the three variable 'a', 'b' and 'c'. It should be clarified that a, b, c are variables.

Davoud

**Comment by jmdana** [comment]
Hello Davoud,

Thanks for your feedback.

It's true that the graph could have a caption but the second line in the documentation is:

"It logs and plots the memory usage of all the variables during the execution of the decorated methods."

What did you think they were?
Jose.
