### ISSUE TITLE
Error installing memprof 

### ISSUE THREAD

**Issue by bamal** [jmdana/memprof#19]
Installed /mnt/home_sq/aboukhdhir/miniconda3/lib/python3.6/site-packages/Cython-0.25.2-py3.6-linux-x86_64.egg
    Processing dependencies for Cython
    Finished processing dependencies for Cython
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2znlkx4y/memprof/setup.py", line 40, in <module>
        class md_easy_install(easy_install):
    TypeError: module.__init__() takes at most 2 arguments (3 given)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2znlkx4y/memprof/

**Comment by jmdana** [comment]
How did you try to install it?

**Comment by bamal** [comment]
I cloned the git repo and used installed the setup and now it is working !
