### ISSUE TITLE
Label figure disappeared 

### ISSUE THREAD

**Issue by bamal** [jmdana/memprof#21]
Can you please fix the problem related to the labels of the figure that disappeared if the space is not sufficient !
![extract_tseries](https://cloud.githubusercontent.com/assets/10996072/25566131/9abfb84e-2da1-11e7-9e45-bfa295d35347.png)

**Comment by jmdana** [comment]
Could you please upload somewhere the logfiles which generate that figure? I need a way to reproduce the issue in order to fix it.
