### ISSUE TITLE
Tracking Python c-API variables

### ISSUE THREAD

**Issue by bamal** [jmdana/memprof#22]
I am executing a c++ module and calling it from Python, 
in the log files I do not have the memory used by the variables called in the c++ module.
Would your library be able only to track the variables called directly from Python code only ?

**Comment by jmdana** [comment]
I have never tested memprof with external C/C++ modules but my guess is that, unless the variable is wrapped within a Python variable known by the interpreter, memprof won't be able to detect it.

In other words, if the Python interpreter doesn't allocate the variable and assign a size to it, memprof has no way to know about it.
